### ISSUE TITLE
Implement horctakeover for HUR pairs

### ISSUE THREAD

**Issue by christian-naenny** [hitachi-vantara/vspone-block-ansible#132]
Currently the split and resync state - among others - is implemented. For a disaster scenario where the primary storage is no longer available, the pairsplit does not work. In such cases a horctakeover needs to be issued.

Suggestion for a playbook structure:
```
---
- name: HUR - Hitachi Universal Replicator Pair
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../ansible_vault_vars/ansible_vault_gateway_var.yml
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  tasks:
    - name: Get UAI gateway token
      hitachivantara.vspone_block.vsp.hv_uaig_token_facts:
        connection_info:
          address: "{{ uai_gateway_address }}"
          username: "{{ vault_gateway_username }}"
          password: "{{ vault_gateway_secret }}"
      register: result_token
      ignore_errors: false

    - name: Perform horctakeover for HUR pair
      hitachivantara.vspone_block.vsp.hv_hur:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: takeover
        spec:
          primary_volume_id: {{ primary_volume }}
          mirror_unit_id: {{ mirror_unit }}
          is_svol_readwriteable: true
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
```
